image:
  - Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: 12.13.0

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - yarn

build_script:
  - cmd: yarn pbuild -w

test: off
