image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn

build_script:
  - cmd: yarn pbuild -w
  - sh: yarn pbuild -l

test: off
